#!/usr/bin/env bash

# shellcheck source=/dev/null
[[ "$VIRTUAL_ENV" == "" ]] && source venv/bin/activate

source config/start.sh

while true; do
    git fetch origin master
    git reset --hard origin/master

    curl -sS "$HEALTHCHECKS_URL"
    timeout --preserve-status --signal=ABRT --verbose --kill-after=5s 5m pip3 install -r requirements.txt
    timeout --preserve-status --signal=QUIT --verbose --kill-after=30s 1h python3 -m bots.matrix.bot subprocess

    echo "Auto merging upstream"
    headCommit="$(git rev-parse HEAD)"
    curl -sS "$HEALTHCHECKS_URL_AUTOMERGE/start"
    git pull --all --prune
    git fetch https://github.com/Teahouse-Studios/akari-bot.git master
    git -c user.email="bot-exozyme-akaribot@xtexx.eu.org" \
        -c user.name="Akari Bot @ exozy.me" \
        merge \
        --no-edit -m "Merge upstream" \
        --signoff --no-stat --no-squash \
        MERGE_HEAD
    if [[ -e ".git/MERGE_HEAD" ]]; then
        echo "Failed to auto-merge"
        git merge --abort
    fi
    if [[ "$headCommit" != "$(git rev-parse HEAD)" ]]; then
        echo "Testing auto-merged code"
        {
            set -xe
            timeout --preserve-status --signal=ABRT --verbose --kill-after=5s 3m pip3 install -r requirements.txt
            timeout --preserve-status --signal=QUIT --verbose --kill-after=5s 1m python3 -m bots.matrix.bot subprocess
            git push
        }
        curl -sS --retry 3 "$HEALTHCHECKS_URL_AUTOMERGE/$?"
    else
        echo "Nothing is merged"
        curl -sS --retry 3 "$HEALTHCHECKS_URL_AUTOMERGE"
    fi
done
