name: 添加花瓣
description: 为你的群组添加一定数量花瓣。
title: "[REQUEST]: 申请添加花瓣"
labels: ["request"]
assignees:
  - Teahouse-Studios/akaribot-admin
body:
  - type: markdown
    attributes:
      value: |
        为防止 AI 相关模块被滥用导致无法持续提供服务，故采用代币制。请填写以下表单来添加花瓣。

        请注意，在申请成功后的 14 天内，若无特殊原因请勿再次申请，否则你的申请会被拒绝。

        如果你认为这些模块对你用处很大，欢迎前往爱发电赞助，这些服务需要我们现实上的资金支持。
  - type: checkboxes
    id: preflight
    attributes:
      label: 开始之前……
      description: 
      options:
        - label: 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
          required: true
        - label: 我是群组的管理员。
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: 聊天平台
      description: 你的账号所在平台。
      options:
        - QQ 群
        - QQ 频道
        - Kook
        - Discord
        - Telegram
    validations:
      required: true
  - type: input
    id: user-id
    attributes:
      label: 用户 ID
      description: 你的 QQ 号/Telegram ID/Discord handle。
      placeholder: e.g. QQ 10000/TG @Example/DC Example#1234
    validations:
      required: true
  - type: input
    id: group-id
    attributes:
      label: 群组 ID
      description: 你的对话 ID，可使用 `whoami` 命令查看。
      placeholder: e.g. QQ|Group|1000000
    validations:
      required: true
  - type: input
    id: request-petals
    attributes:
      label: 花瓣数量
      description: 你估计想为群组申请的花瓣数量。
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 理由
      description: 如果你需要较多的花瓣，请向我们说明理由，否则会被削减或拒绝。
      placeholder: 
    validations:
      required: false
